apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: s5lu17suw-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:88d98098f67815dfe525e76006a60632e0dc3b23@sha256:18fc1759eea7b2376b48acddc0bb59c83b244d7ec8b1f4acea8ba4327f7db57d
          name: container-image
