apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: s5lu17suw-go 
  janus-idp.io/tekton: s5lu17suw-go
  backstage.io/kubernetes-id: s5lu17suw-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: s5lu17suw-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml